<script lang="ts">
  import { auth } from '$lib/stores/auth'; import { goto } from '$app/navigation'; import { onMount } from 'svelte';
  let username=$state(''); let password=$state(''); let error=$state(''); let loading=$state(false);
  onMount(()=>{auth.init();if($auth.isAuthenticated)goto('/dashboard')});
  async function handleSubmit(e:Event){e.preventDefault();error='';loading=true;const result=await auth.login(username,password);if(result.success)goto('/dashboard');else error=result.error||'No se pudo iniciar sesión';loading=false}
</script>
<svelte:head><title>Iniciar sesión · DocuTrust</title></svelte:head>
<div class="auth-layout"><div class="auth-aside"><span class="aside-mark anim-pop">✓</span><p class="eyebrow anim-rise">Acceso seguro</p><h1 class="anim-rise d1">Tus documentos,<br><em>bajo control.</em></h1><p class="anim-rise d2">Firma y verifica archivos con evidencia criptográfica en cada paso.</p><div class="aside-points anim-rise d3"><span>✓ Claves privadas protegidas</span><span>✓ Historial de versiones</span></div></div><section class="auth-card anim-pop"><div class="mobile-brand">DocuTrust</div><span class="eyebrow">Bienvenido de vuelta</span><h2>Iniciar sesión</h2><p class="intro">Ingresa tus credenciales para continuar.</p>{#if error}<div class="alert error anim-shake" role="alert">⚠ {error}</div>{/if}<form onsubmit={handleSubmit}><label for="username">Usuario<input id="username" type="text" bind:value={username} placeholder="Tu nombre de usuario" required disabled={loading} autocomplete="username"></label><label for="password">Contraseña<input id="password" type="password" bind:value={password} placeholder="Tu contraseña" required disabled={loading} autocomplete="current-password"></label><button class="submit btn-anim" class:is-loading={loading} type="submit" disabled={loading}>{loading?'Validando…':'Iniciar sesión'} <span>→</span></button></form><p class="switch">¿Aún no tienes una cuenta? <a href="/register">Crear cuenta</a></p><details class="anim-fade d5"><summary>Usuarios de demostración</summary><div class="demo"><code>admin</code><span>Admin123!@#</span><code>carlos</code><span>Carlos123!@#</span></div></details></section></div>
<style>
  .auth-layout{min-height:calc(100vh - 164px);display:grid;grid-template-columns:1fr 1fr;align-items:center;gap:70px;max-width:960px;margin:auto;padding:30px 0}.auth-aside{padding:30px 0}.aside-mark{width:49px;height:49px;display:grid;place-items:center;background:#d1fae5;color:#047857;border-radius:15px;font-size:1.5rem;font-weight:900;margin-bottom:30px}.eyebrow{font-size:.7rem;color:#4f46e5;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.auth-aside h1{font-size:clamp(2.6rem,5vw,4.3rem);line-height:1.02;letter-spacing:-.06em;color:#101b3d;margin:15px 0}.auth-aside h1 em{font-style:normal;color:#4f46e5}.auth-aside>p:not(.eyebrow){max-width:380px;color:#64748b;line-height:1.7}.aside-points{display:grid;gap:10px;margin-top:30px;color:#475569;font-size:.8rem;font-weight:650}.auth-card{background:#fff;border:1px solid #e1e7f0;border-radius:19px;padding:34px;box-shadow:0 18px 50px rgba(30,41,59,.09)}.mobile-brand{display:none}.auth-card h2{font-size:1.8rem;letter-spacing:-.04em;color:#101b3d;margin:10px 0 5px}.intro{color:#64748b;font-size:.86rem;margin-bottom:26px}.auth-card label{display:grid;gap:7px;margin-bottom:16px;color:#334155;font-size:.77rem;font-weight:750}.auth-card input{width:100%;padding:12px 13px;border:1px solid #d9e1ec;border-radius:9px;background:#fbfdff;color:#17213a}.auth-card input:focus{outline:0;border-color:#4f46e5;box-shadow:0 0 0 3px rgba(79,70,229,.12)}.submit{width:100%;border:0;border-radius:9px;background:#4f46e5;color:#fff;padding:13px;font-weight:800;cursor:pointer;display:flex;justify-content:center;gap:16px;margin-top:6px}.submit:hover:not(:disabled){background:#4338ca}.submit:disabled{opacity:.55;cursor:not-allowed}.switch{text-align:center;margin:22px 0;color:#64748b;font-size:.78rem}.switch a{color:#4f46e5;font-weight:800;text-decoration:none}.auth-card details{border-top:1px solid #edf1f6;padding-top:15px;color:#64748b;font-size:.74rem}.auth-card summary{cursor:pointer;text-align:center}.demo{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px;background:#f8fafc;padding:11px;border-radius:8px}.demo code{color:#4338ca;font-size:.7rem}.demo span{font-size:.7rem;color:#475569}@media(max-width:760px){.auth-layout{grid-template-columns:1fr;max-width:470px}.auth-aside{display:none}.mobile-brand{display:block;color:#4f46e5;font-weight:900;margin-bottom:25px}}@media(max-width:500px){.auth-layout{padding:12px 0}.auth-card{padding:25px 20px}}
.auth-card input {
    transition: border-color 0.18s, box-shadow 0.18s;
  }
  .submit:active:not(:disabled) {
    transform: scale(0.98);
  }
  .demo {
    animation: slideDown 0.3s ease both;
  }
</style>
