<script lang="ts">
  import { auth } from '$lib/stores/auth'; import { goto } from '$app/navigation'; import { onMount } from 'svelte';
  let username=$state(''); let email=$state(''); let fullName=$state(''); let password=$state(''); let confirmPassword=$state(''); let error=$state(''); let success=$state(''); let loading=$state(false);
  onMount(()=>{auth.init();if($auth.isAuthenticated)goto('/dashboard')});
  async function handleSubmit(e:Event){e.preventDefault();error='';success='';if(password!==confirmPassword){error='Las contraseñas no coinciden';return}if(password.length<12){error='La contraseña debe tener al menos 12 caracteres';return}loading=true;const result=await auth.register(username,email,password,fullName);if(result.success){success='Cuenta creada. Redirigiendo al inicio de sesión…';setTimeout(()=>goto('/login'),1600)}else error=result.error||'No se pudo crear la cuenta';loading=false}
</script>
<svelte:head><title>Crear cuenta · DocuTrust</title></svelte:head>
<div class="auth-layout"><div class="auth-aside"><span class="aside-mark anim-pop">+</span><p class="eyebrow anim-rise">Empieza a proteger</p><h1 class="anim-rise d1">Una base segura<br>para cada <em>acuerdo.</em></h1><p class="anim-rise d2">Crea tu espacio documental y conserva una prueba verificable de cada cambio.</p><div class="aside-points anim-rise d3"><span>✓ Firma automática por versión</span><span>✓ Verificación pública con QR</span></div></div><section class="auth-card anim-pop"><div class="mobile-brand">DocuTrust</div><span class="eyebrow">Nuevo espacio</span><h2>Crear cuenta</h2><p class="intro">Completa tus datos para configurar tus claves de firma.</p>{#if error}<div class="alert error anim-shake" role="alert">⚠ {error}</div>{/if}{#if success}<div class="alert success anim-slide" role="status">✓ {success}</div>{/if}<form onsubmit={handleSubmit}><label for="fullName">Nombre completo<input id="fullName" type="text" bind:value={fullName} placeholder="Ej. Ana García" required disabled={loading} autocomplete="name"></label><label for="username">Nombre de usuario<input id="username" type="text" bind:value={username} placeholder="ana.garcia" required disabled={loading} autocomplete="username"></label><label for="email">Correo electrónico<input id="email" type="email" bind:value={email} placeholder="tu@correo.com" required disabled={loading} autocomplete="email"></label><div class="row"><label for="password">Contraseña<input id="password" type="password" bind:value={password} placeholder="Mínimo 12 caracteres" required disabled={loading} autocomplete="new-password"></label><label for="confirmPassword">Confirmar<input id="confirmPassword" type="password" bind:value={confirmPassword} placeholder="Repite la contraseña" required disabled={loading} autocomplete="new-password"></label></div><p class="hint">Usa mayúsculas, minúsculas, números y un carácter especial.</p><button class="submit btn-anim" class:is-loading={loading} type="submit" disabled={loading}>{loading?'Creando cuenta…':'Crear cuenta'} <span>→</span></button></form><p class="switch">¿Ya tienes una cuenta? <a href="/login">Iniciar sesión</a></p></section></div>
<style>
  .auth-layout{min-height:calc(100vh - 164px);display:grid;grid-template-columns:1fr 1fr;align-items:center;gap:65px;max-width:960px;margin:auto;padding:30px 0}.auth-aside{padding:30px 0}.aside-mark{width:49px;height:49px;display:grid;place-items:center;background:#e0e7ff;color:#4338ca;border-radius:15px;font-size:1.5rem;font-weight:900;margin-bottom:30px}.eyebrow{font-size:.7rem;color:#4f46e5;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.auth-aside h1{font-size:clamp(2.5rem,5vw,4.2rem);line-height:1.02;letter-spacing:-.06em;color:#101b3d;margin:15px 0}.auth-aside h1 em{font-style:normal;color:#4f46e5}.auth-aside>p:not(.eyebrow){max-width:380px;color:#64748b;line-height:1.7}.aside-points{display:grid;gap:10px;margin-top:30px;color:#475569;font-size:.8rem;font-weight:650}.auth-card{background:#fff;border:1px solid #e1e7f0;border-radius:19px;padding:31px;box-shadow:0 18px 50px rgba(30,41,59,.09)}.mobile-brand{display:none}.auth-card h2{font-size:1.8rem;letter-spacing:-.04em;color:#101b3d;margin:10px 0 5px}.intro{color:#64748b;font-size:.84rem;margin-bottom:21px}.auth-card label{display:grid;gap:7px;margin-bottom:13px;color:#334155;font-size:.74rem;font-weight:750;flex:1}.auth-card input{width:100%;padding:11px 12px;border:1px solid #d9e1ec;border-radius:9px;background:#fbfdff;color:#17213a}.auth-card input:focus{outline:0;border-color:#4f46e5;box-shadow:0 0 0 3px rgba(79,70,229,.12)}.row{display:flex;gap:10px}.hint{color:#94a3b8;font-size:.69rem;margin:-2px 0 15px}.submit{width:100%;border:0;border-radius:9px;background:#4f46e5;color:#fff;padding:13px;font-weight:800;cursor:pointer;display:flex;justify-content:center;gap:16px}.submit:hover:not(:disabled){background:#4338ca}.submit:disabled{opacity:.55}.switch{text-align:center;margin-top:20px;color:#64748b;font-size:.77rem}.switch a{color:#4f46e5;font-weight:800;text-decoration:none}.alert{padding:11px 13px;border-radius:9px;font-size:.76rem;margin-bottom:16px}.alert.error{background:#fff1f2;border:1px solid #fecdd3;color:#be123c}.alert.success{background:#ecfdf5;border:1px solid #bbf7d0;color:#047857}@media(max-width:760px){.auth-layout{grid-template-columns:1fr;max-width:470px}.auth-aside{display:none}.mobile-brand{display:block;color:#4f46e5;font-weight:900;margin-bottom:25px}}@media(max-width:500px){.auth-layout{padding:12px 0}.auth-card{padding:24px 19px}.row{display:grid;gap:0}}
.auth-card input {
    transition: border-color 0.18s, box-shadow 0.18s;
  }
  .submit:active:not(:disabled) {
    transform: scale(0.98);
  }
</style>
