<script lang="ts">
  import { api } from '$lib/api'; import { page } from '$app/stores';
  let verifyFile=$state<File|null>(null); let verifyResult=$state<any>(null); let verifying=$state(false); let error=$state('');
  $effect(()=>{const id=$page.url.searchParams.get('doc');if(id)loadInfo(id)});
  async function loadInfo(id:string){const result=await api.getVerificationInfo(id);if(result.success&&result.data)verifyResult={type:'info',data:result.data}}
  function choose(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(f){verifyFile=f;verifyResult=null;error=''}}
  async function submit(e:Event){e.preventDefault();if(!verifyFile)return;verifying=true;error='';const r=await api.verifyDocument(verifyFile);if(r.success&&r.data)verifyResult={type:'verify',data:r.data};else error=r.error||'No se pudo verificar el archivo';verifying=false}
  function color(s:string){return s==='VALID'?'#059669':s==='NOT_FOUND'?'#d97706':'#dc2626'} function label(s:string){return s==='VALID'?'Documento íntegro':s==='MANIPULATED'?'Documento manipulado':s==='INVALID_SIGNATURE'?'Firma inválida':s==='FOUND'?'Coincidencia encontrada':'Documento no encontrado'}
</script>
<svelte:head><title>Verificar documento · DocuTrust</title></svelte:head>
<div class="verify-page"><div class="intro anim-rise"><span class="eyebrow">Verificación pública</span><h1>Comprueba la autenticidad<br>de un documento.</h1><p>Sube el archivo original para comparar su hash y validar la firma digital registrada.</p></div><section class="verify-card anim-pop d1"><form onsubmit={submit}><label class="drop" class:has-file={verifyFile} for="file"><span class="drop-icon">↥</span><strong>{verifyFile?'Archivo listo para verificar':'Arrastra o selecciona tu archivo'}</strong><small>{verifyFile ? verifyFile.name + ' · ' + (verifyFile.size/1024).toFixed(1) + ' KB' : 'PDF, Word o texto · máximo 10 MB'}</small><input id="file" type="file" onchange={choose} required disabled={verifying}></label><button class="submit" type="submit" disabled={verifying||!verifyFile}>{verifying?'Analizando integridad…':'Verificar documento'} <span>→</span></button></form>{#if error}<div class="alert error anim-shake">⚠ {error}</div>{/if}{#if verifyResult}{#if verifyResult.type==='info'}<div class="result info anim-pop"><span class="result-icon">i</span><div><strong>{verifyResult.data.document.title}</strong><p>Versión actual: v{verifyResult.data.document.currentVersion} · Firmado por {verifyResult.data.signature.signedBy}</p><small>Sube el archivo para confirmar su integridad.</small></div></div>{:else}<div class="result anim-pop" style={'--accent:'+color(verifyResult.data.status)}><div class="result-head"><span class="status-icon">{verifyResult.data.status==='VALID'?'✓':'!'}</span><div><strong>{label(verifyResult.data.status)}</strong><p>{verifyResult.data.message}</p></div></div>{#if verifyResult.data.verification}<div class="checks stagger"><div><span>Hash SHA-256</span><b class:bad={!verifyResult.data.verification.hashMatch}>{verifyResult.data.verification.hashMatch?'Coincide':'No coincide'}</b></div><div><span>Firma digital</span><b class:bad={!verifyResult.data.verification.signatureValid}>{verifyResult.data.verification.signatureValid?'Válida':'Inválida'}</b></div></div><small class="signed">Firmado por <b>{verifyResult.data.verification.signedBy}</b> · {verifyResult.data.verification.signedAt}</small>{/if}</div>{/if}{/if}</section><p class="legal">La firma criptográfica es válida dentro de DocuTrust y no constituye firma electrónica certificada.</p></div>
<style>
  .verify-page{max-width:760px;margin:auto;padding:24px 0}.intro{margin-bottom:27px}.eyebrow{font-size:.7rem;color:#4f46e5;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.intro h1{font-size:clamp(2rem,5vw,3.4rem);line-height:1.06;letter-spacing:-.055em;color:#101b3d;margin:12px 0}.intro p{max-width:590px;color:#64748b;font-size:.95rem;line-height:1.65}.verify-card{background:#fff;border:1px solid #e1e7f0;border-radius:17px;padding:25px;box-shadow:0 15px 40px rgba(30,41,59,.07)}.drop{display:grid;place-items:center;gap:7px;min-height:190px;border:1.5px dashed #bec9dc;border-radius:13px;background:#f8fafc;color:#475569;cursor:pointer;text-align:center;padding:20px}.drop:hover,.drop.has-file{border-color:#818cf8;background:#eef2ff}.drop-icon{width:40px;height:40px;display:grid;place-items:center;background:#e0e7ff;color:#4f46e5;border-radius:12px;font-size:1.5rem;font-weight:900}.drop strong{font-size:.9rem}.drop small{color:#94a3b8;font-size:.72rem}.drop input{display:none}.submit{width:100%;margin-top:14px;padding:13px;border:0;border-radius:9px;background:#4f46e5;color:#fff;font-weight:800;cursor:pointer;display:flex;justify-content:center;gap:16px}.submit:hover:not(:disabled){background:#4338ca}.submit:disabled{opacity:.55}.alert{padding:11px;border-radius:9px;margin-top:15px;font-size:.77rem}.error{background:#fff1f2;border:1px solid #fecdd3;color:#be123c}.result{--accent:#4f46e5;margin-top:19px;border:1px solid #e1e7f0;border-left:4px solid var(--accent);border-radius:11px;padding:18px}.result-head,.result.info{display:flex;gap:12px;align-items:flex-start}.status-icon,.result-icon{width:31px;height:31px;display:grid;place-items:center;border-radius:50%;background:#eef2ff;color:var(--accent);font-weight:900;flex:none}.result-head strong,.result.info strong{font-size:1rem;color:#17213a}.result-head p,.result.info p{font-size:.78rem;color:#64748b;margin-top:4px}.checks{display:grid;grid-template-columns:1fr 1fr;gap:10px;border-top:1px solid #edf1f6;border-bottom:1px solid #edf1f6;margin:16px 0;padding:13px 0}.checks span,.checks b{display:block}.checks span{font-size:.69rem;color:#94a3b8}.checks b{font-size:.8rem;color:#059669;margin-top:4px}.checks b.bad{color:#dc2626}.signed{color:#64748b;font-size:.72rem}.legal{color:#92400e;background:#fffbeb;border:1px solid #fde68a;border-radius:9px;padding:12px;margin-top:15px;font-size:.7rem}@media(max-width:520px){.verify-page{padding-top:8px}.verify-card{padding:16px}.checks{grid-template-columns:1fr}}
.drop {
    transition: border-color 0.18s, background 0.18s, transform 0.18s;
  }
  .drop:hover {
    transform: translateY(-1px);
  }
  .drop.has-file .drop-icon {
    animation: ringPulse 2s ease-out infinite;
  }
  .submit {
    transition: background 0.18s, transform 0.18s, opacity 0.18s;
  }
  .submit:active:not(:disabled) {
    transform: scale(0.98);
  }
</style>
